#!/bin/bash

SERVER_NAME="${SERVER_NAME:-LAN-slide Retrocycles}"
SERVER_CFG="usr/etc/games/Retrocycles-dedicated/autoexec.cfg"
MASTER_PORT="${MASTER_PORT:-4533}"
RCON_PASSWORD="${RCON_PASSWORD:-lanslide}"

MAX_CLIENTS="${MAX_CLIENTS:-16}"
MESSAGE_OF_DAY="${MESSAGE_OF_DAY:-}"
MAP_FILE="${MAP_FILE:-Anonymous\/polygon\/regular\/square-1.0.1.aamap.xml}"
ARENA_AXES="${ARENA_AXES:-4}"

CYCLE_BRAKE="${CYCLE_BRAKE:-30}"
CYCLE_SPEED="${CYCLE_SPEED:-30}"
CYCLE_START_SPEED="${CYCLE_START_SPEED:-20}"
CYCLE_TURN_SPEED_FACTOR="${CYCLE_TURN_SPEED_FACTOR:-0.95}"

LIMIT_SCORE="${LIMIT_SCORE:-100}"
LIMIT_ROUNDS="${LIMIT_ROUNDS:-10}"
LIMIT_TIME="${LIMIT_TIME:-30}"
MIN_PLAYERS="${MIN_PLAYERS:-0}"
NUM_AIS="${NUM_AIS:-0}"
SCORE_WIN="${SCORE_WIN:-10}"
SIZE_FACTOR="${SIZE_FACTOR:--3}"
TEAM_BALANCE_WITH_AIS="${TEAM_BALANCE_WITH_AIS:-0}"

TEAM_MAX_PLAYERS="${TEAM_MAX_PLAYERS:-1}"

SCORE_SUICIDE="${SCORE_SUICIDE:--4}"
SCORE_KILL="${SCORE_KILL:-3}"
SCORE_DIE="${SCORE_DIE:--2}"

sed -i "s/\$SERVER_NAME/$SERVER_NAME/" $SERVER_CFG
sed -i "s/\$MASTER_PORT/$MASTER_PORT/" $SERVER_CFG
sed -i "s/\$RCON_PASSWORD/$RCON_PASSWORD/" $SERVER_CFG

sed -i "s/\$CYCLE_BRAKE/$CYCLE_BRAKE/" $SERVER_CFG
sed -i "s/\$CYCLE_SPEED/$CYCLE_SPEED/" $SERVER_CFG
sed -i "s/\$CYCLE_START_SPEED/$CYCLE_START_SPEED/" $SERVER_CFG
sed -i "s/\$CYCLE_TURN_SPEED_FACTOR/$CYCLE_TURN_SPEED_FACTOR/" $SERVER_CFG

sed -i "s/\$MAX_CLIENTS/$MAX_CLIENTS/" $SERVER_CFG
sed -i "s/\$MESSAGE_OF_DAY/$MESSAGE_OF_DAY/" $SERVER_CFG
sed -i "s|\$MAP_FILE|$MAP_FILE|" $SERVER_CFG
sed -i "s/\$ARENA_AXES/$ARENA_AXES/" $SERVER_CFG

sed -i "s/\$LIMIT_SCORE/$LIMIT_SCORE/" $SERVER_CFG
sed -i "s/\$LIMIT_ROUNDS/$LIMIT_ROUNDS/" $SERVER_CFG
sed -i "s/\$LIMIT_TIME/$LIMIT_TIME/" $SERVER_CFG
sed -i "s/\$MIN_PLAYERS/$MIN_PLAYERS/" $SERVER_CFG
sed -i "s/\$NUM_AIS/$NUM_AIS/" $SERVER_CFG
sed -i "s/\$SCORE_WIN/$SCORE_WIN/" $SERVER_CFG
sed -i "s/\$SIZE_FACTOR/$SIZE_FACTOR/" $SERVER_CFG
sed -i "s/\$TEAM_BALANCE_WITH_AIS/$TEAM_BALANCE_WITH_AIS/" $SERVER_CFG
sed -i "s/\$SCORE_SUICIDE/$SCORE_SUICIDE/" $SERVER_CFG
sed -i "s/\$SCORE_KILL/$SCORE_KILL/" $SERVER_CFG
sed -i "s/\$SCORE_DIE/$SCORE_DIE/" $SERVER_CFG

sed -i "s/\$TEAM_MAX_PLAYERS/$TEAM_MAX_PLAYERS/" $SERVER_CFG

./Retrocycles_Dedicated
