#!/bin/bash

SERVER_NAME="${SERVER_NAME:-LAN-slide Retrocycles}"
SERVER_CFG="usr/etc/games/Retrocycles-dedicated/autoexec.cfg"
MASTER_PORT="${MASTER_PORT:-4533}"

MAX_CLIENTS="${MAX_CLIENTS:-16}"
MESSAGE_OF_DAY="${MESSAGE_OF_DAY:-}"
MAP_FILE="${MAP_FILE:-Anonymous\/polygon\/regular\/square-1.0.1.aamap.xml}"
ARENA_AXES="${ARENA_AXES:-4}"

CYCLE_BRAKE="${CYCLE_BRAKE:-30}"
CYCLE_SPEED="${CYCLE_SPEED:-30}"
CYCLE_START_SPEED="${CYCLE_START_SPEED:-20}"
CYCLE_TURN_SPEED_FACTOR="${CYCLE_TURN_SPEED_FACTOR:-0.95}"

LIMIT_SCORE="${LIMIT_SCORE:-100}"
LIMIT_ROUNDS="${LIMIT_ROUNDS:-10}"
LIMIT_TIME="${LIMIT_TIME:-30}"

SP_LIMIT_SCORE="${SP_LIMIT_SCORE:-100000}"
SP_LIMIT_ROUNDS="${SP_LIMIT_ROUNDS:-10}"
SP_LIMIT_TIME="${SP_LIMIT_TIME:-30}"
SP_MIN_PLAYERS="${SP_MIN_PLAYERS:-0}"
SP_NUM_AIS="${SP_NUM_AIS:-0}"
SP_SCORE_WIN="${SP_SCORE_WIN:-10}"
SP_SIZE_FACTOR="${SP_SIZE_FACTOR:--3}"
SP_TEAM_BALANCE_WITH_AIS="${SP_TEAM_BALANCE_WITH_AIS:-0}"

SCORE_WIN="${SCORE_WIN:-10}"
SCORE_SUICIDE="${SCORE_SUICIDE:--4}"
SCORE_KILL="${SCORE_KILL:-3}"
SCORE_DIE="${SCORE_DIE:--2}"

sed -i "s/\$SERVER_NAME/$SERVER_NAME/" $SERVER_CFG
sed -i "s/\$MASTER_PORT/$MASTER_PORT/" $SERVER_CFG

sed -i "s/\$CYCLE_BRAKE/$CYCLE_BRAKE/" $SERVER_CFG
sed -i "s/\$CYCLE_SPEED/$CYCLE_SPEED/" $SERVER_CFG
sed -i "s/\$CYCLE_START_SPEED/$CYCLE_START_SPEED/" $SERVER_CFG
sed -i "s/\$CYCLE_TURN_SPEED_FACTOR/$CYCLE_TURN_SPEED_FACTOR/" $SERVER_CFG

sed -i "s/\$MAX_CLIENTS/$MAX_CLIENTS/" $SERVER_CFG
sed -i "s/\$MESSAGE_OF_DAY/$MESSAGE_OF_DAY/" $SERVER_CFG
sed -i "s|\$MAP_FILE|$MAP_FILE|" $SERVER_CFG
sed -i "s/\$ARENA_AXES/$ARENA_AXES/" $SERVER_CFG

sed -i "s/\$LIMIT_SCORE/$LIMIT_SCORE/" $SERVER_CFG
sed -i "s/\$LIMIT_ROUNDS/$LIMIT_ROUNDS/" $SERVER_CFG
sed -i "s/\$LIMIT_TIME/$LIMIT_TIME/" $SERVER_CFG

sed -i "s/\$SP_LIMIT_SCORE/$SP_LIMIT_SCORE/" $SERVER_CFG
sed -i "s/\$SP_LIMIT_ROUNDS/$SP_LIMIT_ROUNDS/" $SERVER_CFG
sed -i "s/\$SP_LIMIT_TIME/$SP_LIMIT_TIME/" $SERVER_CFG
sed -i "s/\$SP_MIN_PLAYERS/$SP_MIN_PLAYERS/" $SERVER_CFG
sed -i "s/\$SP_NUM_AIS/$SP_NUM_AIS/" $SERVER_CFG
sed -i "s/\$SP_SCORE_WIN/$SP_SCORE_WIN/" $SERVER_CFG
sed -i "s/\$SP_SIZE_FACTOR/$SP_SIZE_FACTOR/" $SERVER_CFG
sed -i "s/\$SP_TEAM_BALANCE_WITH_AIS/$SP_TEAM_BALANCE_WITH_AIS/" $SERVER_CFG

sed -i "s/\$SCORE_WIN/$SCORE_WIN/" $SERVER_CFG
sed -i "s/\$SCORE_SUICIDE/$SCORE_SUICIDE/" $SERVER_CFG
sed -i "s/\$SCORE_KILL/$SCORE_KILL/" $SERVER_CFG
sed -i "s/\$SCORE_DIE/$SCORE_DIE/" $SERVER_CFG

./Retrocycles_Dedicated
