#!/bin/bash

ENV_VAR_ARR='SERVER_NAME MAX_PLAYERS RCON_PASSWORD SV_PASSWORD Z_DIFFICULTY FORCE_UNRESERVED L4D_INFECTED_LIMIT L4D_KILLRESERVATION L4D_SURVIVOR_LIMIT L4D_STATIC_MINIMUM_SURVIVOR'
SUPERVERSUS_ARR='FORCE_UNRESERVED L4D_INFECTED_LIMIT L4D_KILLRESERVATION L4D_SURVIVOR_LIMIT L4D_STATIC_MINIMUM_SURVIVOR L4D_AUTOJOIN CI_BACKGROUND_MOB_SIZE CI_COMMON_MOB_LIMIT_SIZE CI_MEGA_MOB_SIZE CI_MOB_SPAWN_FINALE_SIZE CI_MOB_SPAWN_MAX_SIZE CI_MOB_SPAWN_MIN_SIZE'
TANK_ARR='L4D_TANK_ON_SPAWN_COUNTLIMIT L4D_TANK_ON_SPAWN_COUNT L4D_TANK_ON_SPAWN_DELAY_MIN L4D_TANK_ON_SPAWN_DELAY_MAX L4D_TANK_ON_SPAWN_ENABLED L4D_TANK_ON_SPAWN_HP'

SERVER_NAME="${SERVER_NAME:-LAN-slide HL2DM}"
MAX_PLAYERS="${MAX_PLAYERS:-8}"
PORT="${PORT:-27015}"
MAP="${MAP:-c1m4_atrium}"
RCON_PASSWORD="${RCON_PASSWORD:-lanslide}"
SV_PASSOWRD="${SV_PASSWORD:-}"
#SV_FLAGS="${SV_FLAGS:-Browser}"
GAME_MODE="${GAME_MODE:-versus}"
Z_DIFFICULTY="${Z_DIFFICULTY:-normal}"
GAME="${GAME:-left4dead2}"
SV_LAN="${SV_LAN:-1}"
SERVER_CFG="${GAME}/cfg/server.cfg"
SUPERVERSUS_CFG="${GAME}/cfg/sourcemod/l4d_superversus.cfg"
TANK_CFG="${GAME}/cfg/sourcemod/l4d_tank_on_spawn.cfg"
#REMOVE_HUMAN_LIMIT="${REMOVE_HUMAN_LIMIT:-1}"

FORCE_UNRESERVED="${FORCE_UNRESERVED:-1}"
L4D_INFECTED_LIMIT="${L4D_INFECTED_LIMIT:-4}"
L4D_KILLRESERVATION="${L4D_KILLRESERVATION:-0}"
L4D_SURVIVOR_LIMIT="${L4D_SURVIVOR_LIMIT:-4}"
L4D_STATIC_MINIMUM_SURVIVOR="${L4D_SURVIVOR_LIMIT:-4}"
L4D_AUTOJOIN="${L4D_AUTOJOIN:-1}"

CI_BACKGROUND_MOB_SIZE="${CI_BACKGROUND_MOB_SIZE:-20.0}"
CI_COMMON_MOB_LIMIT_SIZE="${CI_COMMON_MOB_LIMIT_SIZE:-30.0}"
CI_MEGA_MOB_SIZE="${CI_MEGA_MOB_SIZE:-50.0}"
CI_MOB_SPAWN_FINALE_SIZE="${CI_MOB_SPAWN_FINALE_SIZE:-20.0}"
CI_MOB_SPAWN_MAX_SIZE="${CI_MOB_SPAWN_MAX_SIZE:-30.0}"
CI_MOB_SPAWN_MIN_SIZE="${CI_MOB_SPAWN_MIN_SIZE:-10.0}"

L4D_TANK_ON_SPAWN_COUNT="${L4D_TANK_ON_SPAWN_COUNT:-50}"
L4D_TANK_ON_SPAWN_COUNTLIMIT="${L4D_TANK_ON_SPAWN_COUNTLIMIT:-50}"
L4D_TANK_ON_SPAWN_DELAY_MIN="${L4D_TANK_ON_SPAWN_DELAY_MIN:-5}"
L4D_TANK_ON_SPAWN_DELAY_MAX="${L4D_TANK_ON_SPAWN_DELAY_MAX:-10}"
L4D_TANK_ON_SPAWN_ENABLED="${L4D_TANK_ON_SPAWN_ENABLED:-1}"
L4D_TANK_ON_SPAWN_HP="${L4D_TANK_ON_SPAWN_HP:-500000}"

for ENV_VAR in $ENV_VAR_ARR
do
     sed -i "s/\$$ENV_VAR/${!ENV_VAR}/" $SERVER_CFG
done

for SUPERVERSUS_VAR in $SUPERVERSUS_ARR
do
     sed -i "s/\$$SUPERVERSUS_VAR/${!SUPERVERSUS_VAR}/" $SUPERVERSUS_CFG
done

for TANK_VAR in $TANK_ARR
do
     sed -i "s/\$$TANK_VAR/${!TANK_VAR}/" $TANK_CFG
done


hostname -I | python3 stats.py &

python3 /l4d2/left4dead2/config_admins.py >> /l4d2/left4dead2/addons/sourcemod/configs/admins_simple.ini && rm /l4d2/left4dead2/config_admins.py -f

./srcds_run -game ${GAME} +map ${MAP} "versus" -console -debug
