FROM minecraft-base
LABEL maintainer="LAN-slide"

ADD start.sh /spigot/

# This fails,
# RUN java -Xms1G -Xmx1G -jar minecraft_server.1.10.2.jar nogui
# TODO: create server.properties, and an eula.txt
CMD ["./start.sh"]
