#FROM sourcemod
FROM almalinux:9

MAINTAINER LAN-slide


RUN useradd steam && mkdir /tf2 && chown steam:steam /tf2

RUN yum update -y && yum install -y epel-release

RUN yum install -y \
    glibc.i686 \
    libstdc++.i686 \
    zlib.i686 \
    python3.9 \ 
    python3-pip 

RUN pip3 install asyncio opengsq

USER steam

COPY --chown=steam:steam data /tf2
COPY --from=sourcemod --chown=steam:steam /csgo /tf2/tf/

WORKDIR /tf2

COPY --chown=steam:steam cfg/server.cfg tf/cfg/server.cfg
COPY --chown=steam:steam entrypoint.sh entrypoint.sh
COPY --chown=steam:steam stats.py stats.py

RUN chmod +x entrypoint.sh

ENTRYPOINT /tf2/entrypoint.sh
