#!/bin/bash

ENV_VAR_ARR='IP UPDATE_PORT PORT DOWNLOAD_MAX_KILOBYTES_PER_SECOND DOWNLOAD_HTTP_SOURCE SERVER_NAME MAX_PLAYER_COUNT HARDCORE AUTO_BALANCE_TEAMS PREVENT_TEAM_SWITCHING DISABLE_BALANCE_TEAMS_POPUP LAN_SERVER CALL_END_OF_ROUND_VOTE DISALLOW_DEMO_USERS RCON_ENABLED RCON_PASSWORD MAX_PING MIN_LEVEL MAX_LEVEL SECRET_CODE CAMERA_VIEW_SCALE_PERCENT NUMBER_OF_BOTS BOT_DIFFICULTY BOTS_BALANCE_TEAMS BOT_SPECTATE_THRESHOLD FFA_SCORE_LIMIT FFA_ROUND_LIMIT FFA_ROUND_TIME_SECONDS FFA_WARMUP_TIME_SECONDS BD_ROUND_LIMIT BD_ROUND_TIME_SECONDS BD_WARMUP_TIME_SECONDS OBJ_GAMES_PER_ROUND OBJ_GAMES_PER_SWITCH_SIDES OBJ_GAMES_WIN_MARGIN OBJ_BETWEEN_GAME_TIME_SECONDS OBJ_ROUND_LIMIT OBJ_ROUND_TIME_SECONDS OBJ_WARMUP_TIME_SECONDS PLANE_GOALS_PER_ROUND PLANE_ROUND_LIMIT PLANE_ROUND_TIME_SECONDS PLANE_WARMUP_TIME_SECONDS TDM_SCORE_LIMIT TDM_ROUND_LIMIT TDM_ROUND_TIME_SECONDS TDM_WARMUP_TIME_SECONDS'
SERVER_SUB_DIR="servers"
SERVER_CFG="launcher_config.xml"

IP="${IP:-}"
UPDATE_PORT="${UPDATE_PORT:-27275}"
PORT="${PORT:-27276}"
DOWNLOAD_MAX_KILOBYTES_PER_SECOND="${DOWNLOAD_MAX_KILOBYTES_PER_SECOND:-40}"
DOWNLOAD_HTTP_SOURCE="${DOWNLOAD_HTTP_SOURCE:-}"
SERVER_NAME="${SERVER_NAME:-'Altitude Server'}"
MAX_PLAYER_COUNT="${MAX_PLAYER_COUNT:-14}"
HARDCORE="${HARDCORE:-true}"
AUTO_BALANCE_TEAMS="${AUTO_BALANCE_TEAMS:-true}"
PREVENT_TEAM_SWITCHING="${PREVENT_TEAM_SWITCHING:-false}"
DISABLE_BALANCE_TEAMS_POPUP="${DISABLE_BALANCE_TEAMS_POPUP:-false}"
LAN_SERVER="${LAN_SERVER:-true}"
CALL_END_OF_ROUND_VOTE="${CALL_END_OF_ROUND_VOTE:-true}"
DISALLOW_DEMO_USERS="${DISALLOW_DEMO_USERS:-false}"
RCON_ENABLED="${RCON_ENABLED:-true}"
RCON_PASSWORD="${RCON_PASSWORD:-adminDocker}"
MAX_PING="${MAX_PING:-350}"
MIN_LEVEL="${MIN_LEVEL:-0}"
MAX_LEVEL="${MAX_LEVEL:-0}"
SECRET_CODE="${SECRET_CODE:-}"
CAMERA_VIEW_SCALE_PERCENT="${CAMERA_VIEW_SCALE_PERCENT:-100}"

# Bots
NUMBER_OF_BOTS="${NUMBER_OF_BOTS:-2}"
BOT_DIFFICULTY="${BOT_DIFFICULTY:-MEDIUM}"
BOTS_BALANCE_TEAMS="${BOTS_BALANCE_TEAMS:-true}"
BOT_SPECTATE_THRESHOLD="${BOT_SPECTATE_THRESHOLD:-6}"

# Free For All
FFA_SCORE_LIMIT="${FFA_SCORE_LIMIT:-0}"
FFA_ROUND_LIMIT="${FFA_ROUND_LIMIT:-1}"
FFA_ROUND_TIME_SECONDS="${FFA_ROUND_TIME_SECONDS:-420}"
FFA_WARMUP_TIME_SECONDS="${FFA_WARMUP_TIME_SECONDS:-10}"

# Base Destroy
BD_ROUND_LIMIT="${BD_ROUND_LIMIT:-1}"
BD_ROUND_TIME_SECONDS="${BD_ROUND_TIME_SECONDS:-0}"
BD_WARMUP_TIME_SECONDS="${BD_WARMUP_TIME_SECONDS:-10}"

# Objective
OBJ_GAMES_PER_ROUND="${OBJ_GAMES_PER_ROUND:-9}"
OBJ_GAMES_PER_SWITCH_SIDES="${OBJ_GAMES_PER_SWITCH_SIDES:-2}"
OBJ_GAMES_WIN_MARGIN="${OBJ_GAMES_WIN_MARGIN:-1}"
OBJ_BETWEEN_GAME_TIME_SECONDS="${OBJ_BETWEEN_GAME_TIME_SECONDS:-6}"
OBJ_ROUND_LIMIT="${OBJ_ROUND_LIMIT:-1}"
OBJ_ROUND_TIME_SECONDS="${OBJ_ROUND_TIME_SECONDS:-0}"
OBJ_WARMUP_TIME_SECONDS="${OBJ_WARMUP_TIME_SECONDS:-10}"

# Plane Ball
PLANE_GOALS_PER_ROUND="${PLANE_GOALS_PER_ROUND:-11}"
PLANE_ROUND_LIMIT="${PLANE_ROUND_LIMIT:-1}"
PLANE_ROUND_TIME_SECONDS="${PLANE_ROUND_TIME_SECONDS:-0}"
PLANE_WARMUP_TIME_SECONDS="${PLANE_WARMUP_TIME_SECONDS:-10}"

# Team Deathmatch
TDM_SCORE_LIMIT="${TDM_SCORE_LIMIT:-0}"
TDM_ROUND_LIMIT="${TDM_ROUND_LIMIT:-1}"
TDM_ROUND_TIME_SECONDS="${TDM_ROUND_TIME_SECONDS:-600}"
TDM_WARMUP_TIME_SECONDS="${TDM_WARMUP_TIME_SECONDS:-10}"

for ENV_VAR in $ENV_VAR_ARR
do
     sed -i "s/\$$ENV_VAR/${!ENV_VAR}/" $SERVER_DIR/$SERVER_SUB_DIR/$SERVER_CFG
done

/opt/scripts/start.sh
