#!/bin/bash

ENV_VAR_ARR='TRACK GAME_MODE SCRIPT_NAME CHAT_TIME FINISHTIMEOUT ALLWARMUPDURATION DISABLERESPAWN FORCESHOWALLOPPONENTS ROUNDS_POINTSLIMIT ROUNDS_USENEWRULES ROUNDS_FORCEDLAPS ROUNDS_NEWRULESPOINTSLIMIT TEAM_POINTSLIMIT TEAM_MAXPOINTS  TEAM_USENEWRULES TIMEATTACK_LIMIT TIMEATTACK_SYNCHSTARTPERIOD'
TM_LOGIN="${TM_LOGIN:-admin}"
TM_PASSWORD="${TM_PASSWORD:-admin}"

USER_DATA="/tm/UserData"
DEFAULT_CFG="dedicated_cfg.default.txt"
SERVER_CFG="dedicated_cfg.txt"
MATCH_CFG="playlist.xml"
TRACK="${TRACK:-Australia 2026_(311081)}"
MAPPACK="${MAPPACK:-Trackmania_esports_2026_(TMX_7414).zip}"
DOWNLOADED="Maps/Downloaded"

GAME_MODE="${GAME_MODE:-0}"
SCRIPT_NAME="${SCRIPT_NAME:-TM_TimeAttack_Online}"
CHAT_TIME="${CHAT_TIME:-1000}"
FINISHTIMEOUT="${FINISHTIMEOUT:-1}"
ALLWARMUPDURATION="${ALLWARMUPDURATION:-0}"
DISABLERESPAWN="${DISABLERESPAWN:-0}"
FORCESHOWALLOPPONENTS="${FORCESHOWALLOPPONENTS:-0}"
ROUNDS_POINTSLIMIT="${ROUNDS_POINTSLIMIT:-50}"
ROUNDS_USENEWRULES="${ROUNDS_USENEWRULES:-0}"
ROUNDS_FORCEDLAPS="${ROUNDS_FORCEDLAPS:-0}"
ROUNDS_NEWRULESPOINTSLIMIT="${ROUNDS_NEWRULESPOINTSLIMIT:-5}"
TEAM_POINTSLIMIT="${TEAM_POINTSLIMIT:-5}"
TEAM_MAXPOINTS="${TEAM_MAXPOINTS:-6}"
TEAM_USENEWRULES="${TEAM_USENEWRULES:-0}"
TIMEATTACK_LIMIT="${TIMEATTACK_LIMIT:-300000}"
TIMEATTACK_SYNCHSTARTPERIOD="${TIMEATTACK_SYNCHSTARTPERIOD:-0}"

# Extract Maps
unzip -o "/tm/${MAPPACK}" -d "${USER_DATA}/${DOWNLOADED}" && rm -f "${MAPPACK}"

# Generate Serve Config
if [[ ! -f "${USER_DATA}/Config/${SERVER_CFG}" ]]; then
    cp "${USER_DATA}/Config/${DEFAULT_CFG}" "${USER_DATA}/Config/${SERVER_CFG}"
fi

xmlstarlet ed -L \
  -u "/dedicated/masterserver_account/login" \
  -v "$TM_LOGIN" \
  -u "/dedicated/masterserver_account/password" \
  -v "$TM_PASSWORD" \
  ${USER_DATA}/Config/${SERVER_CFG}

# Update Match Settings
for ENV_VAR in $ENV_VAR_ARR
do
     sed -i "s/\$$ENV_VAR/${!ENV_VAR}/" ${USER_DATA}/Maps/MatchSettings/${MATCH_CFG}
done

./TrackmaniaServer /dedicated_cfg=${SERVER_CFG} /game_settings=MatchSettings/${MATCH_CFG}
bash
